# Generated by Django 5.1.6 on 2025-02-26 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_alter_loginattempt_last_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='last_attempt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
