# Generated by Django 5.1.6 on 2025-02-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_customuser_delete_mfa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
