# Generated by Django 5.1.6 on 2025-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0009_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
